language: node_js
node_js:
- 6.2.0
deploy:
  provider: modulus
  project_name: shandyclub
  api_key:
    secure: LBQ3wOjKKWaTGH5T3ck1h8SViPI6EhvmGayXXk82NPnD7wGwIYE0ARi93MDAof4VbVhtA/p4JyASFPdU55MaGO44oREEe68RNi0lXXUn+SLzN12fYlmb4lEkHgHANJo7Lx8WzD37c/KFWAnSpY+TXZ6iTB5f+u1/hP6C3BAjzuTkDM+eaLyqor6NWtWaiNlSqCW3KCZmG0GPG8Aj7cFLiGTHR+dVWdb5dI+JWkKTWPupQZlmh92/QAXpL0wfIqk6tI/mVZFwWez2OU0FWrki3ik7O5i5sSPRCOSJymw1zZv8CAhi2ge+APv35OSJZNP2k1NwaqOmifoNfYiIiZ36bu2Wwtgz1oqA08ZKZ4rmzBGJg0RqNTVkHxElMAsNfgdlPau8aELMZWZZBXYlGDTVZTmMnAjfDwTGW8fXdobrkb4jnAj+3V8PIIcOXUoLSNg3XVk7/HdhvOsQMiMG+HOe0TWsKisdrS4VW2Hjl/XwbAqQLKm4w4qboybuWoiY6sE0+khlGrMP6r0HRhVlvWhQpqNDCpm7mewU7M59B/MRBMeH1LvY9UATu7kEcBg7WqhMxFjlHbnfgNkwmcfeq4UHGolsFsHrGsR/1wzRG0IL/4cW+braGbj+nOfFyk8W9fSg5Bn6X0ZgMg9IdKbSodk5/qoGxF/XqJMJ76SgaTUa8Y8=
